config/routes.rb
BallGame::Application.routes.draw do
  resources :game_types

  resources :teams

  resources :games

  match "/auth/:provider/callback" => "sessions#create"

  match "/signout" => "sessions#destroy", :as => :signout

   root :to => 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :team
  belongs_to :game_type

  validates_presence_of :date, :team_1_id, :team_2_id, :game_type_id
  validate :check_teams

  def check_teams
    errors.add(:team_2_id, "cannot be same as Team 1") if team_1_id == team_2_id
  end

  def self.saved?
    true
  end
end

app/models/game_type.rb
class GameType < ActiveRecord::Base
  has_many :games
  
  validates_presence_of :name
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :games
  validates_presence_of :name

  validates :home_town, :length => {:minimum => 3}
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.create_with_omniauth(auth)
    create! do |user| 
    user.provider = auth["provider"] 
    user.uid = auth["uid"]
    user.name = auth["info"]["name"] 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/game_types_controller.rb
class GameTypesController < ApplicationController
  # GET /game_types
  # GET /game_types.json
  def index
    @game_types = GameType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @game_types }
    end
  end

  # GET /game_types/1
  # GET /game_types/1.json
  def show
    @game_type = GameType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game_type }
    end
  end

  # GET /game_types/new
  # GET /game_types/new.json
  def new
    @game_type = GameType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game_type }
    end
  end

  # GET /game_types/1/edit
  def edit
    @game_type = GameType.find(params[:id])
  end

  # POST /game_types
  # POST /game_types.json
  def create
    @game_type = GameType.new(params[:game_type])

    respond_to do |format|
      if @game_type.save
        format.html { redirect_to @game_type, notice: 'Game type was successfully created.' }
        format.json { render json: @game_type, status: :created, location: @game_type }
      else
        format.html { render action: "new" }
        format.json { render json: @game_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /game_types/1
  # PUT /game_types/1.json
  def update
    @game_type = GameType.find(params[:id])

    respond_to do |format|
      if @game_type.update_attributes(params[:game_type])
        format.html { redirect_to @game_type, notice: 'Game type was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @game_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_types/1
  # DELETE /game_types/1.json
  def destroy
    @game_type = GameType.find(params[:id])
    @game_type.destroy

    respond_to do |format|
      format.html { redirect_to game_types_url }
      format.json { head :ok }
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json

include GamesHelper

  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])
    @team_1 = team_object(@game.team_1_id)
    @team_2 = team_object(@game.team_2_id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teams }
    end
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
    @team = Team.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @team }
    end
  end

  # GET /teams/new
  # GET /teams/new.json
  def new
    @team = Team.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @team }
    end
  end

  # GET /teams/1/edit
  def edit
    @team = Team.find(params[:id])
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(params[:team])

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render json: @team, status: :created, location: @team }
      else
        format.html { render action: "new" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teams/1
  # PUT /teams/1.json
  def update
    @team = Team.find(params[:id])

    respond_to do |format|
      if @team.update_attributes(params[:team])
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team = Team.find(params[:id])
    @team.destroy

    respond_to do |format|
      format.html { redirect_to teams_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_types_helper.rb
module GameTypesHelper
end

app/helpers/games_helper.rb
module GamesHelper

  def team_object(team_id)
    team_name = Team.find(team_id).name
  end


end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/game_types/_form.html.erb
<%= form_for(@game_type) do |f| %>
  <% if @game_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game_type.errors.count, "error") %> prohibited this game_type from being saved:</h2>

      <ul>
      <% @game_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/game_types/edit.html.erb
<h1>Editing game_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_type %> |
<%= link_to 'Back', game_types_path %>

app/views/game_types/index.html.erb
<h1>Listing game_types</h1>

<table>
  <td><%= link_to 'Games', games_path %></td>
  <td><%= link_to 'Teams', teams_path %></td>
  <td><%= link_to 'Game Types', game_types_path %></td>
</table>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @game_types.each do |game_type| %>
  <tr>
    <td><%= game_type.name %></td>
    <td><%= link_to 'Show', game_type %></td>
    <td><%= link_to 'Edit', edit_game_type_path(game_type) %></td>
    <td><%= link_to 'Destroy', game_type, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game type', new_game_type_path %>

app/views/game_types/new.html.erb
<h1>New game_type</h1>

<%= render 'form' %>

<%= link_to 'Back', game_types_path %>

app/views/game_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @game_type.name %>
</p>


<%= link_to 'Edit', edit_game_type_path(@game_type) %> |
<%= link_to 'Back', game_types_path %>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %>*<br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :team_1_id %>*<br />
    <%= collection_select(:game, :team_1_id, Team.all, :id, :name, :prompt => true) %>
  </div>
  <div class="field">
    <%= f.label :team_2_id %>*<br />
    <%= collection_select(:game, :team_2_id, Team.all, :id, :name, :prompt => true) %>
  </div>
  <div class="field">
    <%= f.label :game_type_id %><br />
    <%= collection_select(:game, :game_type_id, GameType.all, :id, :name, :prompt => true) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

  <p>* Required</p>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Take Me Out to the Ball Game!</h1>
<h3>Current Game Listings</h3>

<table>
  <td><%= link_to 'Games', games_path %></td>
  <td><%= link_to 'Teams', teams_path %></td>
  <td><%= link_to 'Game Types', game_types_path %></td>
</table>

<table>
  <tr>
    <th>Id</th>
    <th>Date</th>
    <th>Team 1</th>
    <th>Team 2</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.id %></td>
    <td><%= game.date %></td>
    <td><%= team_object(game.team_1_id) %></td>
    <td><%= team_object(game.team_2_id) %></td>
    <td><%= game.game_type.name %></td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @game.id %>
</p>

<p>
  <b>Date:</b>
  <%= @game.date %>
</p>

<p>
  <b>Team 1:</b>
  <%= @team_1 %>
</p>

<p>
  <b>Team 2:</b>
  <%= @team_2 %>
</p>

<p>
  <b>Game Type:</b>
  <%= @game.game_type.name %>
</p>



<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BallGame</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %> <div class="flash" id="<%= key %>">
<%= value %> </div>
<% end %>
<div id="user_nav">
  <% if current_user %>
    Welcome, <%= current_user.name %>!
    <%= link_to "Sign out", signout_path %>
  <% else %>
    <%= link_to "Sign in with Twitter", "/auth/twitter" %>
  <% end %>
</div>
<%= yield %>

</body>
</html>